### ISSUE TITLE
misconfigured bouncer doesn't error

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/cs-standalone-php-bouncer#13]
Following misconfiguration leads to the bouncer not complaining, but not blocking anything :
 - Having an invalid LAPI URL
 - Having a misconfigured lapi API Key

**Comment by buixor** [comment]
This can be solved by enabling : `display_errors` in the configuration file

**Comment by julienloizelet** [comment]
@buixor : I tested with a 0.18.0 of the lib : 
if there is an invalid URL or Api key, error are logged in the `prod.log` (and in the `debug.log` too if the `debug_log` settings is set to true.

Using the `display_errors` settings will throw an error : depending on the webserver, this errors can appears on the browser (with my nginx setup, this is what happen). It seems that with apache, error are not shown in the browser but i did not tested it.

By default, `display_errors` is set to false and this is the expected behavior: a bouncer error should not break the user exeperience : 

> If there is any technical problem while bouncing, don't block the user. Bypass bouncing and log the error.

**Comment by julienloizelet** [comment]
Closing because the new version 1.0.0 is a total redesign.
Thanks
